/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalSupportRouteImport } from './routes/legal.support'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AuthenticatedAiArenaIndexRouteImport } from './routes/_authenticated/ai-arena.index'
import { Route as AuthenticatedAiArenaHistoryRouteImport } from './routes/_authenticated/ai-arena.history'
import { Route as AuthenticatedCareerIndexRouteImport } from './routes/_authenticated/career.index'
import { Route as AuthenticatedChartSymbolRouteImport } from './routes/_authenticated/chart.$symbol'
import { Route as AuthenticatedCompeteIndexRouteImport } from './routes/_authenticated/compete.index'
import { Route as AuthenticatedCompeteIdRouteImport } from './routes/_authenticated/compete.$id'
import { Route as AuthenticatedCareerMilestoneIdRouteImport } from './routes/_authenticated/career.milestone.$id'
import { Route as AuthenticatedCompeteJoinCodeRouteImport } from './routes/_authenticated/compete.join.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSupportRoute = LegalSupportRouteImport.update({
  id: '/legal/support',
  path: '/legal/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiArenaIndexRoute =
  AuthenticatedAiArenaIndexRouteImport.update({
    id: '/ai-arena/',
    path: '/ai-arena/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiArenaHistoryRoute =
  AuthenticatedAiArenaHistoryRouteImport.update({
    id: '/ai-arena/history',
    path: '/ai-arena/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerIndexRoute =
  AuthenticatedCareerIndexRouteImport.update({
    id: '/career/',
    path: '/career/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChartSymbolRoute =
  AuthenticatedChartSymbolRouteImport.update({
    id: '/chart/$symbol',
    path: '/chart/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompeteIndexRoute =
  AuthenticatedCompeteIndexRouteImport.update({
    id: '/compete/',
    path: '/compete/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompeteIdRoute = AuthenticatedCompeteIdRouteImport.update({
  id: '/compete/$id',
  path: '/compete/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerMilestoneIdRoute =
  AuthenticatedCareerMilestoneIdRouteImport.update({
    id: '/career/milestone/$id',
    path: '/career/milestone/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompeteJoinCodeRoute =
  AuthenticatedCompeteJoinCodeRouteImport.update({
    id: '/compete/join/$code',
    path: '/compete/join/$code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/support': typeof LegalSupportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/ai-arena/history': typeof AuthenticatedAiArenaHistoryRoute
  '/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/compete/$id': typeof AuthenticatedCompeteIdRoute
  '/ai-arena/': typeof AuthenticatedAiArenaIndexRoute
  '/career/': typeof AuthenticatedCareerIndexRoute
  '/compete/': typeof AuthenticatedCompeteIndexRoute
  '/career/milestone/$id': typeof AuthenticatedCareerMilestoneIdRoute
  '/compete/join/$code': typeof AuthenticatedCompeteJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/support': typeof LegalSupportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/ai-arena/history': typeof AuthenticatedAiArenaHistoryRoute
  '/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/compete/$id': typeof AuthenticatedCompeteIdRoute
  '/ai-arena': typeof AuthenticatedAiArenaIndexRoute
  '/career': typeof AuthenticatedCareerIndexRoute
  '/compete': typeof AuthenticatedCompeteIndexRoute
  '/career/milestone/$id': typeof AuthenticatedCareerMilestoneIdRoute
  '/compete/join/$code': typeof AuthenticatedCompeteJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/auth': typeof AuthRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/support': typeof LegalSupportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/ai-arena/history': typeof AuthenticatedAiArenaHistoryRoute
  '/_authenticated/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/_authenticated/compete/$id': typeof AuthenticatedCompeteIdRoute
  '/_authenticated/ai-arena/': typeof AuthenticatedAiArenaIndexRoute
  '/_authenticated/career/': typeof AuthenticatedCareerIndexRoute
  '/_authenticated/compete/': typeof AuthenticatedCompeteIndexRoute
  '/_authenticated/career/milestone/$id': typeof AuthenticatedCareerMilestoneIdRoute
  '/_authenticated/compete/join/$code': typeof AuthenticatedCompeteJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/auth'
    | '/challenges'
    | '/home'
    | '/insights'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/trade'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/support'
    | '/legal/terms'
    | '/ai-arena/history'
    | '/chart/$symbol'
    | '/compete/$id'
    | '/ai-arena/'
    | '/career/'
    | '/compete/'
    | '/career/milestone/$id'
    | '/compete/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/auth'
    | '/challenges'
    | '/home'
    | '/insights'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/trade'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/support'
    | '/legal/terms'
    | '/ai-arena/history'
    | '/chart/$symbol'
    | '/compete/$id'
    | '/ai-arena'
    | '/career'
    | '/compete'
    | '/career/milestone/$id'
    | '/compete/join/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-deletion'
    | '/auth'
    | '/_authenticated/challenges'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/trade'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/support'
    | '/legal/terms'
    | '/_authenticated/ai-arena/history'
    | '/_authenticated/chart/$symbol'
    | '/_authenticated/compete/$id'
    | '/_authenticated/ai-arena/'
    | '/_authenticated/career/'
    | '/_authenticated/compete/'
    | '/_authenticated/career/milestone/$id'
    | '/_authenticated/compete/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountDeletionRoute: typeof AccountDeletionRoute
  AuthRoute: typeof AuthRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSupportRoute: typeof LegalSupportRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/support': {
      id: '/legal/support'
      path: '/legal/support'
      fullPath: '/legal/support'
      preLoaderRoute: typeof LegalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-arena/': {
      id: '/_authenticated/ai-arena/'
      path: '/ai-arena'
      fullPath: '/ai-arena/'
      preLoaderRoute: typeof AuthenticatedAiArenaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-arena/history': {
      id: '/_authenticated/ai-arena/history'
      path: '/ai-arena/history'
      fullPath: '/ai-arena/history'
      preLoaderRoute: typeof AuthenticatedAiArenaHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career/': {
      id: '/_authenticated/career/'
      path: '/career'
      fullPath: '/career/'
      preLoaderRoute: typeof AuthenticatedCareerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chart/$symbol': {
      id: '/_authenticated/chart/$symbol'
      path: '/chart/$symbol'
      fullPath: '/chart/$symbol'
      preLoaderRoute: typeof AuthenticatedChartSymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compete/': {
      id: '/_authenticated/compete/'
      path: '/compete'
      fullPath: '/compete/'
      preLoaderRoute: typeof AuthenticatedCompeteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compete/$id': {
      id: '/_authenticated/compete/$id'
      path: '/compete/$id'
      fullPath: '/compete/$id'
      preLoaderRoute: typeof AuthenticatedCompeteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career/milestone/$id': {
      id: '/_authenticated/career/milestone/$id'
      path: '/career/milestone/$id'
      fullPath: '/career/milestone/$id'
      preLoaderRoute: typeof AuthenticatedCareerMilestoneIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compete/join/$code': {
      id: '/_authenticated/compete/join/$code'
      path: '/compete/join/$code'
      fullPath: '/compete/join/$code'
      preLoaderRoute: typeof AuthenticatedCompeteJoinCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedAiArenaHistoryRoute: typeof AuthenticatedAiArenaHistoryRoute
  AuthenticatedChartSymbolRoute: typeof AuthenticatedChartSymbolRoute
  AuthenticatedCompeteIdRoute: typeof AuthenticatedCompeteIdRoute
  AuthenticatedAiArenaIndexRoute: typeof AuthenticatedAiArenaIndexRoute
  AuthenticatedCareerIndexRoute: typeof AuthenticatedCareerIndexRoute
  AuthenticatedCompeteIndexRoute: typeof AuthenticatedCompeteIndexRoute
  AuthenticatedCareerMilestoneIdRoute: typeof AuthenticatedCareerMilestoneIdRoute
  AuthenticatedCompeteJoinCodeRoute: typeof AuthenticatedCompeteJoinCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedAiArenaHistoryRoute: AuthenticatedAiArenaHistoryRoute,
  AuthenticatedChartSymbolRoute: AuthenticatedChartSymbolRoute,
  AuthenticatedCompeteIdRoute: AuthenticatedCompeteIdRoute,
  AuthenticatedAiArenaIndexRoute: AuthenticatedAiArenaIndexRoute,
  AuthenticatedCareerIndexRoute: AuthenticatedCareerIndexRoute,
  AuthenticatedCompeteIndexRoute: AuthenticatedCompeteIndexRoute,
  AuthenticatedCareerMilestoneIdRoute: AuthenticatedCareerMilestoneIdRoute,
  AuthenticatedCompeteJoinCodeRoute: AuthenticatedCompeteJoinCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountDeletionRoute: AccountDeletionRoute,
  AuthRoute: AuthRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSupportRoute: LegalSupportRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
